In [4]:
# import pandas and numpy packages
import pandas as pd
import numpy as np

# Creat features list
column_names=['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape', 'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'Class']

In [5]:
# Import data from internet
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data', names=column_names)

In [6]:
data.describe()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
count        6.990000e+02       699.000000               699.000000   
mean         1.071704e+06         4.417740                 3.134478   
std          6.170957e+05         2.815741                 3.051459   
min          6.163400e+04         1.000000                 1.000000   
25%          8.706885e+05         2.000000                 1.000000   
50%          1.171710e+06         4.000000                 1.000000   
75%          1.238298e+06         6.000000                 5.000000   
max          1.345435e+07        10.000000                10.000000   

       Uniformity of Cell Shape  Marginal Adhesion  \
count                699.000000         699.000000   
mean                   3.207439           2.806867   
std                    2.971913           2.855379   
min                    1.000000           1.000000   
25%                    1.000000           1.000000   
50%                    1.000000           1.000000   
75%                    5.000000           4.000000   
max                   10.000000          10.000000   

       Single Epithelial Cell Size  Bland Chromatin  Normal Nucleoli  \
count                   699.000000       699.000000       699.000000   
mean                      3.216023         3.437768         2.866953   
std                       2.214300         2.438364         3.053634   
min                       1.000000         1.000000         1.000000   
25%                       2.000000         2.000000         1.000000   
50%                       2.000000         3.000000         1.000000   
75%                       4.000000         5.000000         4.000000   
max                      10.000000        10.000000        10.000000   

          Mitoses       Class  
count  699.000000  699.000000  
mean     1.589413    2.689557  
std      1.715078    0.951273  
min      1.000000    2.000000  
25%      1.000000    2.000000  
50%      1.000000    2.000000  
75%      1.000000    4.000000  
max     10.000000    4.000000

In [7]:
data.count()

Sample code number             699
Clump Thickness                699
Uniformity of Cell Size        699
Uniformity of Cell Shape       699
Marginal Adhesion              699
Single Epithelial Cell Size    699
Bare Nuclei                    699
Bland Chromatin                699
Normal Nucleoli                699
Mitoses                        699
Class                          699
dtype: int64

In [8]:
# Replace missing data with '?'
data = data.replace(to_replace='?', value=np.nan)

# Discard items with missing data
data = data.dropna(how='any')

In [9]:
data.describe()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
count        6.830000e+02       683.000000               683.000000   
mean         1.076720e+06         4.442167                 3.150805   
std          6.206440e+05         2.820761                 3.065145   
min          6.337500e+04         1.000000                 1.000000   
25%          8.776170e+05         2.000000                 1.000000   
50%          1.171795e+06         4.000000                 1.000000   
75%          1.238705e+06         6.000000                 5.000000   
max          1.345435e+07        10.000000                10.000000   

       Uniformity of Cell Shape  Marginal Adhesion  \
count                683.000000         683.000000   
mean                   3.215227           2.830161   
std                    2.988581           2.864562   
min                    1.000000           1.000000   
25%                    1.000000           1.000000   
50%                    1.000000           1.000000   
75%                    5.000000           4.000000   
max                   10.000000          10.000000   

       Single Epithelial Cell Size  Bland Chromatin  Normal Nucleoli  \
count                   683.000000       683.000000       683.000000   
mean                      3.234261         3.445095         2.869693   
std                       2.223085         2.449697         3.052666   
min                       1.000000         1.000000         1.000000   
25%                       2.000000         2.000000         1.000000   
50%                       2.000000         3.000000         1.000000   
75%                       4.000000         5.000000         4.000000   
max                      10.000000        10.000000        10.000000   

          Mitoses       Class  
count  683.000000  683.000000  
mean     1.603221    2.699854  
std      1.732674    0.954592  
min      1.000000    2.000000  
25%      1.000000    2.000000  
50%      1.000000    2.000000  
75%      1.000000    4.000000  
max     10.000000    4.000000

In [10]:
data.count()

Sample code number             683
Clump Thickness                683
Uniformity of Cell Size        683
Uniformity of Cell Shape       683
Marginal Adhesion              683
Single Epithelial Cell Size    683
Bare Nuclei                    683
Bland Chromatin                683
Normal Nucleoli                683
Mitoses                        683
Class                          683
dtype: int64

In [11]:
data.shape

(683, 11)

In [12]:
data.head

<bound method NDFrame.head of      Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
5               1017122                8                       10   
6               1018099                1                        1   
7               1018561                2                        1   
8               1033078                2                        1   
9               1033078                4                        2   
10              1035283                1                        1   
11              1036172                2                        1   
12              1041801                5                        3   
13  

In [13]:
# Split the data with train_test_split and choose 75% for training and 25% for testing randomly
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data[column_names[1:10]], data[column_names[10]], test_size=0.25, random_state=33)
y_train.value_counts()

C:\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


2    344
4    168
Name: Class, dtype: int64

In [14]:
X_train.describe()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
count       512.000000               512.000000                512.000000   
mean          4.324219                 3.076172                  3.111328   
std           2.791579                 3.021135                  2.925244   
min           1.000000                 1.000000                  1.000000   
25%           2.000000                 1.000000                  1.000000   
50%           4.000000                 1.000000                  1.000000   
75%           6.000000                 4.000000                  5.000000   
max          10.000000                10.000000                 10.000000   

       Marginal Adhesion  Single Epithelial Cell Size  Bland Chromatin  \
count         512.000000                   512.000000        512.00000   
mean            2.757812                     3.169922          3.34375   
std             2.841532                     2.222557          2.41631   
min             1.000000                     1.000000          1.00000   
25%             1.000000                     2.000000          2.00000   
50%             1.000000                     2.000000          3.00000   
75%             3.000000                     4.000000          4.00000   
max            10.000000                    10.000000         10.00000   

       Normal Nucleoli     Mitoses  
count       512.000000  512.000000  
mean          2.744141    1.582031  
std           2.977897    1.696407  
min           1.000000    1.000000  
25%           1.000000    1.000000  
50%           1.000000    1.000000  
75%           3.000000    1.000000  
max          10.000000   10.000000

In [15]:
y_test.value_counts()

2    100
4     71
Name: Class, dtype: int64

In [16]:
# Import 标准化 from sklearn to scale the data
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from scipy import stats
ss=StandardScaler()

In [17]:
# Scale the data
X_train = ss.fit_transform(X_train)

In [18]:
X_test = ss.fit_transform(X_test)

In [19]:
X_train[0:3,:]

array([[-1.19196677, -0.68788787, -0.03809494, -0.61921941, -0.52690038,
        -0.6689353 , -0.55666054, -0.58626819, -0.34343195],
       [-1.19196677,  0.30608745, -0.03809494,  2.55118397,  0.37384418,
         1.86597741,  0.68611648,  1.09441105, -0.34343195],
       [ 0.24231522, -0.02523765, -0.72246721, -0.61921941, -0.52690038,
        -0.6689353 , -0.97091955, -0.58626819, -0.34343195]])

In [20]:
stats.describe(X_test)

DescribeResult(nobs=171, minmax=(array([-1.31898582, -0.74601605, -0.80203241, -0.70056629, -1.09640363,
       -0.79166185, -1.08955212, -0.69374911, -0.36324158]), array([1.80877871, 2.08186251, 2.05520805, 2.37992376, 2.96953659,
       1.54237568, 2.47815152, 2.08666723, 4.54051973])), mean=array([-1.35044672e-16, -2.07761034e-17,  3.11641551e-17,  1.55820775e-17,
       -5.19402585e-17,  5.19402585e-17, -1.03880517e-17,  3.11641551e-17,
       -5.19402585e-17]), variance=array([1.00588235, 1.00588235, 1.00588235, 1.00588235, 1.00588235,
       1.00588235, 1.00588235, 1.00588235, 1.00588235]), skewness=array([0.48204156, 1.02428567, 0.92776671, 1.33126365, 1.25565039,
       0.69008292, 0.84828846, 1.12099736, 3.28367865]), kurtosis=array([-0.83100281, -0.45391156, -0.57529356,  0.40814522,  0.62835832,
       -1.3427985 , -0.42786041, -0.33647082, 10.39717159]))

In [21]:
# The means are actually 0
X_train.mean(axis=0)

array([-5.55111512e-17,  6.33174069e-17,  1.99493200e-17, -4.33680869e-18,
        6.24500451e-17,  4.33680869e-18,  1.12757026e-17, -4.16333634e-17,
        4.51028104e-17])

In [22]:
X_train.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
lr = LogisticRegression()

In [24]:
sgdc = SGDClassifier()

In [25]:
lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [26]:
lr_y_predict = lr.predict(X_test)

In [27]:
sgdc.fit(X_train, y_train)

C:\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [28]:
sgdc_y_predict = sgdc.predict(X_test)

In [29]:
from sklearn.metrics import classification_report

In [30]:
print('Accuracy of LR Classifier:', lr.score(X_test, y_test))
print(classification_report(y_test, lr_y_predict, target_names=['Benigh', 'Malignant']))

Accuracy of LR Classifier: 0.9707602339181286
             precision    recall  f1-score   support

     Benigh       0.96      0.99      0.98       100
  Malignant       0.99      0.94      0.96        71

avg / total       0.97      0.97      0.97       171



In [31]:
print('Accuracy of SGD Classifier:', sgdc.score(X_test, y_test))
print(classification_report(y_test, sgdc_y_predict, target_names=['Benigh', 'Malignant']))

Accuracy of SGD Classifier: 0.9824561403508771
             precision    recall  f1-score   support

     Benigh       0.98      0.99      0.99       100
  Malignant       0.99      0.97      0.98        71

avg / total       0.98      0.98      0.98       171

